name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project Sift.xcodeproj

      - name: Build and test (Simulator)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          set -e
          xcodebuild \
            -project Sift.xcodeproj \
            -scheme Sift \
            -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            clean test | xcpretty

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: ~/Library/Logs

