name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Show environment
        run: |
          xcodebuild -version
          xcrun simctl list devices

      # 1) Build once for testing (fast, re-used by both destinations)
      - name: Build for testing
        run: |
          set -euo pipefail
          xcodebuild build-for-testing \
            -project Sift.xcodeproj \
            -scheme Sift \
            -destination 'platform=iOS Simulator,name=iPad (10th generation)' \
            -enableCodeCoverage YES

      # 2) Run tests on iPad first (uses the build above)
      - name: Test (iPad first)
        run: |
          set -euo pipefail
          xcodebuild test-without-building \
            -project Sift.xcodeproj \
            -scheme Sift \
            -destination 'platform=iOS Simulator,name=iPad (10th generation)' \
            -enableCodeCoverage YES

      # 3) Run tests on iPhone (second)
      - name: Test (iPhone second)
        run: |
          set -euo pipefail
          xcodebuild test-without-building \
            -project Sift.xcodeproj \
            -scheme Sift \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -enableCodeCoverage YES

      - name: Save DerivedData (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DerivedData
          path: ~/Library/Developer/Xcode/DerivedData
          if-no-files-found: ignore

      - name: Save Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-logs
          path: "*.log"
          if-no-files-found: ignore
